Repository proga-react-practice/xi-team-project, pull requests merged in 2024-05, with the labels that each got.

#7 Fixes and updates in AI page
  package-lock.json
  src/components/AI/Cards.tsx
  src/components/AI/Form/CustomFormControl.tsx
  src/components/AI/Form/Form.tsx
  src/components/ScrollContainer.tsx
  src/pages/AI.tsx
Labels: needs changes

#8 Layout fix
  index.html
  src/components/AI/Cards.tsx
  src/components/Menu/MainNavigation.tsx
  src/constants.ts
  src/index.css
  src/main.tsx
  src/pages/AI.tsx
  src/pages/Error.tsx
Labels: ready for merge

#9 feat: layout+modal+route
  src/components/FinalCard.tsx
  src/components/Footer.tsx
  src/components/Games/Cards.tsx
  src/components/Games/Form.tsx
  src/components/Menu/MainNavigation.tsx
  src/components/Menu/Tabs.ts
  src/components/context/GamesCardsContextProvider.tsx
  src/images/AI-in-Gaming.png
  src/index.css
  src/pages/AI.tsx
  src/pages/Games.tsx
  src/pages/Home.tsx
  src/pages/MixCards.tsx
  src/pages/Root.tsx
  src/router.tsx
  src/routes.tsx
Labels: ready for merge

#11 Changes for final page
  src/assets/react.svg
  src/components/AI/Cards bug.tsx
  src/components/AI/Cards.tsx
  src/components/AI/Cards/AICardComponent.tsx
  src/components/AI/Cards/Cards.tsx
  src/components/AI/Form/Form.tsx
  src/components/AI/inputDataAssets.ts
  src/components/Alert.tsx
  src/components/Cards/CardsInfo.tsx
  src/components/Cards/CardsInfoMix.tsx
  src/components/Cards/FinalCard.tsx
  src/components/Cards/ICardsInfoProps.ts
  src/components/Cards/ModalCardBox.tsx
  src/components/FinalCard.tsx
  src/components/Games/Cards.tsx
  src/components/Menu/MainNavigation.tsx
  src/components/context/AICardsContextProvider.tsx
  src/components/context/GamesCardsContextProvider.tsx
  src/main.tsx
  src/pages/AI.tsx
  src/pages/Home.tsx
  src/pages/MixCards.tsx
  src/routes.tsx
Labels: ready for merge

#12 feat: added search + drag&drop + some small fixes
  src/components/Footer.tsx
  src/components/Games/Cards.tsx
  src/components/Games/Form.tsx
  src/components/context/GamesCardsContextProvider.tsx
  src/pages/Games.tsx
Labels: ready for merge

#16 Update README.md
  README.md
Labels: ready for merge

#13 fixes: warnings, unused code, reused components, error page link, hyphenation and other
  src/components/AI/Cards/Cards.tsx
  src/components/Cards/BasisCard.tsx
  src/components/Cards/CardChip.tsx
  src/components/Cards/CardsInfo.tsx
  src/components/Cards/CardsInfoMix.tsx
  src/components/Cards/FinalCard.tsx
  src/components/Games/Cards.tsx
  src/components/Games/Form.tsx
  src/components/context/AICardsContextProvider.tsx
  src/components/context/GamesCardsContextProvider.tsx
  src/components/context/useAICardsContext.tsx
  src/components/context/useGamesCardsContext.tsx
  src/pages/AI.tsx
  src/pages/Games.tsx
  src/pages/MixCards.tsx
  staticwebapp.config.json
Labels: ready for merge

#14 fix: added some changes to searching+ form layout on mobile + changed edit
  src/components/Games/Cards.tsx
  src/components/Games/Form.tsx
  src/pages/AI.tsx
  src/pages/Games.tsx
  src/pages/MixCards.tsx
Labels: ready for merge

#17 Small fixes in README.md
  README.md
Labels: needs review

#18 fix: added small padding to mixed cards on medium screen
  src/components/Cards/FinalCard.tsx
Labels: needs review
